// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, body, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, title, body, created_at, updated_at
`

type CreatePostParams struct {
	ID    string
	Title string
	Body  string
}

// 新しい記事を挿入して挿入結果をそのまま返す (RETURNING *)
// created_at / updated_at は DB 側で NOW() をセットするので渡す必要がない
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.ID, arg.Title, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1
`

// 指定 ID の記事を削除する。戻り値は削除された行数 (0 なら対象なし)
func (q *Queries) DeletePost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPost = `-- name: GetPost :one
SELECT id, title, body, created_at, updated_at
FROM posts
WHERE id = $1
`

// 指定 ID の記事を1件取得する。存在しない場合は pgx.ErrNoRows が返る
func (q *Queries) GetPost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many

SELECT id, title, body, created_at, updated_at
FROM posts
ORDER BY created_at DESC
`

// sqlc がこのファイルを読んで型安全な Go コードを自動生成する。
// コメント行の ":many / :one / :exec / :execrows" が戻り値の型を決める。
// 全記事を作成日時の降順 (新しい順) で取得する
func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title      = $1,
    body       = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, title, body, created_at, updated_at
`

type UpdatePostParams struct {
	Title string
	Body  string
	ID    string
}

// タイトル・本文を更新して更新後のレコードを返す
// updated_at も DB 側で NOW() にする
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.Title, arg.Body, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
